# Generated by Django 3.2.15 on 2022-09-08 21:34

from django.db import migrations, models
import django.db.models.deletion
import user_app.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(upload_to='profile-images/', verbose_name='Profile Image')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('phone', models.CharField(max_length=10, unique=True, validators=[user_app.validators.validate_phone_number], verbose_name='Phone No.')),
                ('dob', models.DateField(verbose_name='Date Of Birth')),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_address', serialize=False, to='user_app.usermodel')),
                ('address_1', models.TextField(verbose_name='Address Line 1')),
                ('address_2', models.TextField(verbose_name='Address Line 2')),
                ('city', models.CharField(max_length=20, verbose_name='City')),
                ('state', models.CharField(max_length=20, verbose_name='State')),
                ('country', models.CharField(max_length=20, verbose_name='Country')),
                ('pincode', models.CharField(max_length=6, validators=[user_app.validators.validate_pincode], verbose_name='Pincode')),
            ],
        ),
    ]
